# Creating Arrays

In [1]:
import numpy as np

In [2]:
A = np.arange(5)
A

array([0, 1, 2, 3, 4])

In [3]:

B = np.array([1,2,3])  # 파이썬 리스트를 numpy ndarray로 변환
B

array([1, 2, 3])

In [4]:
D = np.ndarray(5)                                        # np.ndarray 이건 뭐지?
D

array([4.64218439e-310, 0.00000000e+000, 1.62691062e+219, 5.41659412e+045,
       3.68404448e-043])

In [5]:
E = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))
E

array([0, 1, 2, 3, 4])

#### 리스트와 array의 차이 : array는 처음부터 element 유형을 지정해서 생성. 지정 되지 않음 다른 타입의 element 추가는 불허
   
   
array는 element들이 연속된 메모리 공간에 배치. 모든 element들이 동일한 크기와 타입을 가져야 한다.

In [6]:
import array as arr

arr1 = arr.array('q', [1,2,3])
arr1.append("4")
arr1.insert(1,6)
arr1

TypeError: an integer is required (got type str)

In [7]:
C = np.array([0,1,2,3, '4'])  # 넘파이도 array이지만, C의 모든 element를 문자열로 해석해서 array의 요건을 맞춰준다. 파이썬 넘파이의 유연함
C

array(['0', '1', '2', '3', '4'], dtype='<U21')

In [8]:
D = np.array(["a", "b", "c", "1", "2", "3"]) 
D

array(['a', 'b', 'c', '1', '2', '3'], dtype='<U1')

# size, shape, ndim

In [9]:
a = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

print(a)

print(a.size)   # 총 element 개수

print(a.ndim)   # 행렬의 축의 개수 (차원수)

print(a.shape)  # 행렬의 모양

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
9
3
(3, 1, 3)


In [10]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

print(b.size)

print(b.ndim)

print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
3
(2, 2, 2)


![dimension](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

![shape](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

Note: Keep in mind that when you print a 3-dimensional NumPy array,   
the text output visualizes the array differently than shown here.   
NumPy’s order for printing n-dimensional arrays is that **the last axis is looped over the fastest, while the first is the slowest.** Which means that np.ones((4,3,2)) would be printed as:   


In [11]:
c = np.ones((4,3,2))
print(c)

print(c.size)

print(c.ndim)

print(c.shape)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
24
3
(4, 3, 2)


In [12]:
d = np.array((1,2,3))                    # 이건 뭐지?
type(d)

numpy.ndarray

# 특수 행렬

In [13]:
d = np.ones([3,3])
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
e = np.zeros([3,3])
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
f = np.random.random([3,3])
f

array([[0.76509075, 0.79343154, 0.28198663],
       [0.32454987, 0.87325932, 0.69122681],
       [0.30235694, 0.41733973, 0.41316578]])

# reshape

In [16]:
data1 = np.array([1,2,3,4,5,6,7,8])
data1


array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
data1.reshape([2,4])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
data1.reshape([4,2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
data2 = np.array([1,2,3,4,5,6,7,8,9])
data2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
data2.reshape([3,3]) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
data2.reshape([9,1])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
data3 = np.arange(10).reshape(2,5)
data3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Type

In [23]:
B = np.array([0,1,2,3,4,5])  
print(B)
print(B.dtype)                 # dtype 은 ndarray의 원소의 데이터 타입 반환
print(type(B),"\n")            # type은  ndarray의 자료형 반환

C = np.array([0,1,2,3,'4',5])
print(C)
print(C.dtype)
print(type(C),"\n")

D = np.array([0,1,2,3,[4,5],6])  
print(D)                                   
print(D.dtype)                    # 파이썬 최상위 클래스는 object, dtype을 object로 지정해서라도 행렬 내 dtype 일치시킴
print(type(D))

[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'> 

['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'> 

[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


/home/aiffel/anaconda3/envs/aiffel/lib/python3.7/site-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


# Array Arithmetic

In [24]:
data = np.array([1,2])
ones = np.ones([1,2])
data


array([1, 2])

In [25]:
ones

array([[1., 1.]])

In [26]:
data + ones

array([[2., 3.]])

In [27]:
data * data

array([1, 4])

In [28]:
data / data

array([1., 1.])

In [29]:
data - ones

array([[0., 1.]])

# aggreagation

In [30]:
c

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
c.max()

1.0

In [32]:
c.min()


1.0

In [33]:
c.sum()

24.0

# in more dimensions

In [34]:
g = np.array([[1,2],[3,4]])
g

array([[1, 2],
       [3, 4]])

In [35]:
d = np.ones([3,3])
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
e = np.zeros([3,3])
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
f = np.random.random([3,3])
f

array([[0.35604286, 0.80992654, 0.7904923 ],
       [0.38217785, 0.85379101, 0.02756789],
       [0.58065511, 0.08820654, 0.70089163]])

In [38]:
dd = np.ones((3,3))
dd

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.shape(d) == np.shape(dd)

True

In [40]:
ee = np.zeros((3,3))
ee

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
ff = np.random.random((3,3))
ff

array([[0.37006351, 0.87638606, 0.47351392],
       [0.53590195, 0.13053184, 0.26807139],
       [0.00374986, 0.10420959, 0.15950971]])

# matrix arithmetic

In [42]:
data2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
data2 + dd

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

In [45]:
data2 * data2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [46]:
data2 - dd

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [47]:
data2 / data2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# broadcasting

In [48]:
data

array([1, 2])

In [49]:
data * 3.3

array([3.3, 6.6])

In [50]:
c = np.array([1,2,3])

In [51]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
data2 * c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [53]:
data2 / c

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [54]:
data2 - c

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

# random

In [55]:
np.random.random()          # 0에서 1사이 실수 난수

0.19057671815328048

In [56]:
np.random.choice([0,1,2,3,4,5,6,7])              # 리스트에서 하나 랜덤

1

In [57]:
np.random.randint(0,100)            # 0 에서 100 사이 정수 난수 1개

58

In [58]:
array = np.random.randint(10, size=(5,3)) 
array

array([[8, 5, 3],
       [1, 6, 0],
       [9, 5, 0],
       [9, 8, 2],
       [0, 5, 4]])

In [59]:
np.random.permutation(10)

array([3, 5, 6, 8, 0, 7, 1, 4, 2, 9])

In [60]:
np.random.permutation([1,2,3,4,5,6,7,8,9,0])

array([6, 4, 5, 3, 2, 0, 8, 9, 7, 1])

In [61]:
np.random.normal(loc = 0, scale =1, size =5 )    # 정규분포를 따르는 난수 생성  평균loc, 표준편차scale, 추출개수 size

array([-1.63332178,  1.65030843, -1.62298337, -1.70279551, -0.20486681])

In [62]:
np.random.uniform(low=-1, high=1, size=5)    # 균등분포 따르는 난수생성, 최소low, 최대high

array([ 0.67913403,  0.24202213, -0.07444419, -0.67733518,  0.79361871])

# dot product

In [63]:
j = data3.reshape([5,-1])
j

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [64]:
k = data1.reshape([2,4])
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
j.dot(k)

array([[  5,   6,   7,   8],
       [ 17,  22,  27,  32],
       [ 29,  38,  47,  56],
       [ 41,  54,  67,  80],
       [ 53,  70,  87, 104]])

# matrix indexing

In [66]:
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
data2[0,1]

2

In [68]:
data2[0,:]

array([1, 2, 3])

In [69]:
data2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [70]:
data2[2,2]

9

In [71]:
data2[:,2]

array([3, 6, 9])

# matrix aggregation

In [72]:
data8 = np.array([[1,2,3],[4,5,2],[7,1,5]])
print(data8, "\n")
print(data2)

[[1 2 3]
 [4 5 2]
 [7 1 5]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
data8.max()

7

In [74]:
data8.min()

1

In [75]:
data8.sum()

30

we can also aggregate across the rows or columns by using the axis parameter:

In [76]:
print(data8.max(axis=0)) # axis = 0 : 열끼리 비교해서
print(data2.max(axis=0))

[7 5 5]
[7 8 9]


In [77]:
print(data8.min(axis=1)) # axis = 1 : 행끼리 비교해서
print(data2.min(axis=1))

[1 2 1]
[1 4 7]


In [78]:
print(data8.sum(axis=0))
print(data2.min(axis=1))

[12  8 10]
[1 4 7]


# transpose

In [ ]:
data5 = np.array([[1,2,3],[4,5,6]])
print(data5)
data5.shape

In [ ]:
data6= data5.T        # row -> column   =  column -> row
print(data6)
data6.shape

In [ ]:
A = np.arange(24).reshape(2,3,4)
print(A,"\n")

print("*"*50)

C = np.transpose(A,(2,1,0)) # np.transpose(A, (2,1,0)) 은 A.T와 정확히 같습니다.
print(C,"\n")

print("*"*50)

B = np.transpose(A, (2,0,1)) # B는 A의 3, 1, 2번째 축을 자신의 1, 2, 3번째 축으로 가진 행렬입니다.
print(B)                       ## B는 (4,2,3)의 shape를 가진 행렬입니다.

# 넘파이 배열에 부등호 연산자를 사용하면 bool 배열 값을 반환한다.


In [ ]:
import numpy as np

def step_function(x):
    return np.array(x > 0)

x = np.arange(-5.0, 5.0, 0.1)
print(x)
print(x.size)

y = step_function(x)
y

In [ ]:
y.dtype

In [ ]:
type(y)

# bool값을 가진 넘파이 배열의 원소를 int로 바꿀 수 있다

첫번째 방법   **astype(np.원하는 자료형)**

In [ ]:
print(y)
z = y.astype(np.int)
z



두번째 방법   **원소의 데이터 타입 재지정**

In [ ]:
print(y)
y = np.array(y, dtype=np.int)
y

[넘파이 연습](http://jalammar.github.io/visual-numpy/)